remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
# Adds /feed.xml RSS feed for better indexing & syndication
- jekyll-feed
url: "https://shyamal.me"
lang: en-US
title: shyamal's space
author: Shyamal Anadkat
author_email: shyamalanadkat@gmail.com
logo: assets/img/logo.png
image: assets/img/logo.png
github_username:  shyamal-anadkat
linkedin_username: zostale
description: something new • ex-Applied AI @ OpenAI • AI Advisor to Startups • On Deck Fellow • Proud Son • Duke + Wisconsin Alum • Building for impact • Venture Scout • Neo Mentor • Duke AI Advisory Board
show_downloads: false
google_analytics: G-38XE3DD209
permalink: /blog/:title/

social:
  name: Shyamal Anadkat
  links:
    - https://github.com/shyamal-anadkat
    - https://www.linkedin.com/in/zostale/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Shyamal Anadkat
      image: /assets/img/logo.png
  - scope:
      path: ""
      type: "pages"
    values:
      image: /assets/img/logo.png
